#!/usr/bin/env bash

_EA_ENVIRONMENT_NAME=package-lifecycle-action

case $(basename "$SHELL") in
  "zsh")
    # shellcheck disable=SC2154,SC1087
    _EA_COLOR_GREEN="%{$fg[green]%}"
    # shellcheck disable=SC2154
    _EA_COLOR_NC="%{$reset_color%}"
  ;;
  *)
    _EA_COLOR_GREEN="\[\e[32m\]"
    _EA_COLOR_NC="\[\e[0m\]"
  ;;
esac

_ea_unset_script_variables() {
  unset _EA_ENVIRONMENT_NAME
  unset _EA_COLOR_GREEN
  unset _EA_COLOR_NC
}

_ea_export_local_variables() {
  echo "Setting up local env variables..."

  GITHUB_TOKEN=$(gh auth token)
  GITHUB_TEST_USER=ovsds
  GITHUB_TEST_ORGANIZATION=ovsds-example-organization
  GITHUB_TEST_IMAGE_NAME=package-lifecycle-action/test-image
  GITHUB_TEST_IMAGE_TAG=test-tag
  GITHUB_TEST_IMAGE_TAG_TO_DELETE=tag-to-delete

  export GITHUB_TOKEN
  export GITHUB_TEST_USER
  export GITHUB_TEST_ORGANIZATION
  export GITHUB_TEST_IMAGE_NAME
  export GITHUB_TEST_IMAGE_TAG
  export GITHUB_TEST_IMAGE_TAG_TO_DELETE
}

_ea_unset_set_local_variables() {
  echo "Cleaning up local envs..."

  unset GITHUB_TOKEN
  unset GITHUB_TEST_USER
  unset GITHUB_TEST_ORGANIZATION
  unset GITHUB_TEST_IMAGE_NAME
  unset GITHUB_TEST_IMAGE_TAG
  unset GITHUB_TEST_IMAGE_TAG_TO_DELETE
}

_ea_set_console_prefix() {
  echo "Setting up console color and prefix..."
  _EA_PREVIOUS_PS1="${PS1}"
  PS1="${_EA_COLOR_GREEN}(${_EA_ENVIRONMENT_NAME})${_EA_COLOR_NC}${PS1}"
}

_ea_unset_console_prefix() {
  echo "Cleaning up console color and prefix..."
  PS1="${_EA_PREVIOUS_PS1}"
  unset _EA_PREVIOUS_PS1
}

_ea_set_active_environment() {
  export _EA_ACTIVE_ENVIRONMENT=$_EA_ENVIRONMENT_NAME
  echo ""
  echo "Environment $_EA_ENVIRONMENT_NAME is activated."
  echo "To deactivate: run 'environment_deactivate'."
}

_ea_unset_active_environment() {
  echo ""
  echo "Environment $_EA_ENVIRONMENT_NAME is deactivated."
  unset _EA_ACTIVE_ENVIRONMENT
}

_environment_activate() {
  if [ -n "$_EA_ACTIVE_ENVIRONMENT" ]; then
      echo "Active env is already set to $_EA_ACTIVE_ENVIRONMENT"
      echo "To deactivate, run 'environment_deactivate'"
      return
  fi

  _ea_export_local_variables
  _ea_set_console_prefix

  _ea_set_active_environment

  unset -f _ea_export_local_variables
  unset -f _ea_set_console_prefix
  unset -f _ea_set_active_environment
  unset -f _environment_activate
}

environment_deactivate() {
  if [ -z "$_EA_ACTIVE_ENVIRONMENT" ]; then
      echo "No active environment to deactivate."
      return
  fi

  _ea_unset_console_prefix
  _ea_unset_set_local_variables
  _ea_unset_script_variables

  _ea_unset_active_environment

  unset -f _ea_unset_console_prefix
  unset -f _ea_unset_set_local_variables
  unset -f _ea_unset_script_variables
  unset -f _ea_unset_active_environment
  unset -f environment_deactivate
}

_environment_activate
