name: E2E

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  e2e-default:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Test Run
        id: test-run
        uses: ./
        with:
          package-name: package-lifecycle-action/test-image
          package-type: container
          tag-regex: "^test-tag$"
          untagged: true
          expire-period-days: 0
          retained-tagged-top: 0
          retain-untagged: true
          dry-run: true

  e2e:
    runs-on: ubuntu-latest
    if: always() && !cancelled()

    needs:
      - e2e-default

    steps:
      - name: Collect Results
        uses: ovsds/collect-needs-result-action@v1
        with:
          needs_json: ${{ toJson(needs) }}
          skip_allowed: false
